fabric:
  capacity_id: AC94517C-39AF-425B-A2FE-1E7D72A8C06D
  capacity_name: akhfabcapacity
artifacts:
  lakehouse_name: ConferenceDataLakehouse
  notebook_name: Load Conference Data
  pipeline_name: ConferenceAttendanceDataPipeline
  semantic_model_name: ConferenceAttendanceSemanticModel
  report_name: AttendanceReport
  table_name: conference_attendance
workspaces:
- name: GIZ West US Training
  id: 6709352c-2ea9-4468-af6b-5d604157a56c
  region: West US
  enabled: true
- name: GIZ East US Training
  id: a1f1aed8-2357-4a12-be22-3956e2104953
  region: East US
  enabled: true
- name: GIZ Central US Training
  id: 91f25483-a8ca-4652-9e70-f060c0566b48
  region: Central US
  enabled: true
